const ACTION_TYPES = {
  CREATE_USER: "CREATE_USER",
  GET_ALL_TASKS:"GET_ALL_TASKS",
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  MODIFY_TASK_SUCCESS: "MODIFY_TASK_SUCCESS",
  MODIFY_PTASK_FAILURE:"MODIFY_PTASK_FAILURE",
  MODIFY_STATUS_TASK_SUCCESS: "MODIFY_STATUS_TASK_SUCCESS",
  MODIFY_STATUS_TASK_FAILURE:"MODIFY_STATUS_TASK_FAILURE"

}
    
 export default ACTION_TYPES