const ACTION_TYPES = {
  CREATE_USER: "CREATE_USER",
  GET_ALL_TASKS:"GET_ALL_TASKS",
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  MODIFY_TASK_SUCCESS: "MODIFY_TASK_SUCCESS",
  MODIFY_TASK_FAILURE:"MODIFY_PTASK_FAILURE",
  MODIFY_STATUS_TASK_SUCCESS: "MODIFY_STATUS_TASK_SUCCESS",
  MODIFY_STATUS_TASK_FAILURE: "MODIFY_STATUS_TASK_FAILURE",
  GET_TASKS_STATUS_ON: "GET_TASKS_STATUS_ON",
  GET_TASKS_STATUS_OFF: "GET_TASKS_STATUS_OFF",
  SET_USER:'SET_USER'

}
    
export default ACTION_TYPES;