const ACTION_TYPES = {
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  MODIFY_STATUS_TASK_SUCCESS: "MODIFY_STATUS_TASK_SUCCESS",
  MODIFY_STATUS_TASK_FAILURE:"MODIFY_STATUS_TASK_FAILURE"
  

}
    
 export default ACTION_TYPES